/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasirentalmotor;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author asus
 */
public class FormSewaMotor extends javax.swing.JFrame {

    /**
     * Creates new form FormSewaMotor
     */
    public FormSewaMotor() {
        initComponents();
        
        setLocationRelativeTo(this);
        
        tanggal();
        
        tfNotransaksiform.disable();
        tfNopolisiform.disable();
        tfHargasewaform.disable();
        tfBiayahelmform.disable();
        tfTotalbayarform.disable(); 
       
        tfJumlahhelmform.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }
            });

        tfLamasewaform.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                hitungBiayaHelm();
            }
        });

    }
    
    public void tanggal(){
        Date tanggal = new Date();
        SimpleDateFormat aa = new SimpleDateFormat("dd-MM-YYYY");
        tfTanggalform.setText(aa.format(tanggal));
    }
    
    private void hitungBiayaHelm() {
    try {
        int jumlahHelm = Integer.parseInt(tfJumlahhelmform.getText().trim());
        int lamaSewa = Integer.parseInt(tfLamasewaform.getText().trim());
        
        int biayaHelm = 5000 * jumlahHelm * lamaSewa;
        
        tfBiayahelmform.setText(Integer.toString(biayaHelm));
    } catch (NumberFormatException ex) {
        // Tangani jika pengguna memasukkan teks yang tidak valid
        tfBiayahelmform.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfNotransaksiform = new javax.swing.JTextField();
        tfTanggalform = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbJenismotorform = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfNopolisiform = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfLamasewaform = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfHargasewaform = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfJumlahhelmform = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfBiayahelmform = new javax.swing.JTextField();
        btnKeluarform = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tfTotalbayarform = new javax.swing.JTextField();
        btnHitungtotalform = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfNamaform = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNikktpform = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamatlengkapform = new javax.swing.JTextArea();
        btnRefreshform = new javax.swing.JButton();

        jLabel10.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel10.setText("Total Bayar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM PENGISIAN DATA SEWA MOTOR");

        jLabel2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel2.setText("No. Transaksi");

        jLabel3.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel3.setText("Tanggal");

        tfNotransaksiform.setBackground(new java.awt.Color(204, 204, 204));
        tfNotransaksiform.setText(" ");
        tfNotransaksiform.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        tfTanggalform.setText(" ");
        tfTanggalform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTanggalformActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("No. Polisi");

        cbJenismotorform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beat", "Scoopy", "Vario", "N-Max", "Aerox", "Vespa Sprint" }));
        cbJenismotorform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJenismotorformActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Motor");

        tfNopolisiform.setBackground(new java.awt.Color(204, 204, 204));
        tfNopolisiform.setText(" ");
        tfNopolisiform.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel6.setText("Harga Sewa /Hari");

        tfLamasewaform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLamasewaformActionPerformed(evt);
            }
        });
        tfLamasewaform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLamasewaformKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel7.setText("Lama Sewa");

        tfHargasewaform.setBackground(new java.awt.Color(204, 204, 204));
        tfHargasewaform.setText(" ");
        tfHargasewaform.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfHargasewaform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargasewaformActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah Helm");

        tfJumlahhelmform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahhelmformActionPerformed(evt);
            }
        });
        tfJumlahhelmform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJumlahhelmformKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel9.setText("Biaya Helm");

        tfBiayahelmform.setBackground(new java.awt.Color(204, 204, 204));
        tfBiayahelmform.setText(" ");
        tfBiayahelmform.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBiayahelmform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBiayahelmformActionPerformed(evt);
            }
        });

        btnKeluarform.setText("Keluar");
        btnKeluarform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarformActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel11.setText("Total yang Harus Dibayar");

        tfTotalbayarform.setBackground(new java.awt.Color(204, 204, 204));
        tfTotalbayarform.setText(" ");
        tfTotalbayarform.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfTotalbayarform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalbayarformActionPerformed(evt);
            }
        });

        btnHitungtotalform.setText("Hitung Total");
        btnHitungtotalform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungtotalformActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel12.setText("Nama Lengkap");

        jLabel13.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel13.setText("NIK KTP");

        tfNikktpform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNikktpformActionPerformed(evt);
            }
        });
        tfNikktpform.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNikktpformKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel14.setText("Alamat Lengkap");

        taAlamatlengkapform.setColumns(20);
        taAlamatlengkapform.setRows(5);
        jScrollPane2.setViewportView(taAlamatlengkapform);

        btnRefreshform.setText("Refresh");
        btnRefreshform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfNikktpform, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbJenismotorform, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfJumlahhelmform, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfBiayahelmform, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfHargasewaform, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(77, 77, 77))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(65, 65, 65)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLamasewaform, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfNopolisiform, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNotransaksiform, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(tfTanggalform, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNamaform, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnKeluarform)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRefreshform)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(btnHitungtotalform, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(tfTotalbayarform, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNotransaksiform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfTanggalform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfNamaform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfNikktpform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfHargasewaform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbJenismotorform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfNopolisiform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfJumlahhelmform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfBiayahelmform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfLamasewaform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTotalbayarform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitungtotalform)
                    .addComponent(btnKeluarform)
                    .addComponent(btnRefreshform))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfHargasewaformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargasewaformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargasewaformActionPerformed

    private void cbJenismotorformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJenismotorformActionPerformed
        // TODO add your handling code here:
        if(cbJenismotorform.getSelectedItem()=="Beat"){
            tfNopolisiform.setText("AB 4563 QQ");
            tfHargasewaform.setText("50000");
        }else if(cbJenismotorform.getSelectedItem()=="Scoopy"){
            tfNopolisiform.setText("AB 3683 AW");
            tfHargasewaform.setText("50000");
        }else if(cbJenismotorform.getSelectedItem()=="Vario"){
            tfNopolisiform.setText("AB 4678 ZR");
            tfHargasewaform.setText("50000");
        }else if(cbJenismotorform.getSelectedItem()=="N-Max"){
            tfNopolisiform.setText("AB 4563 RR");
            tfHargasewaform.setText("60000");
        }else if(cbJenismotorform.getSelectedItem()=="Aerox"){
            tfNopolisiform.setText("AB 4646 DM");
            tfHargasewaform.setText("60000");
        }else if(cbJenismotorform.getSelectedItem()=="Vespa Sprint"){
            tfNopolisiform.setText("AB 4635 RY");
            tfHargasewaform.setText("85000");
        }
    }//GEN-LAST:event_cbJenismotorformActionPerformed

    private void tfJumlahhelmformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahhelmformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahhelmformActionPerformed

    private void tfBiayahelmformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBiayahelmformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBiayahelmformActionPerformed

    private void btnKeluarformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarformActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("KELUAR");
        if(JOptionPane.showConfirmDialog(frame, "Apakah kamu ingin keluar?", "KELUAR",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarformActionPerformed

    private void tfTotalbayarformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalbayarformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalbayarformActionPerformed

    private void btnHitungtotalformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungtotalformActionPerformed
        // TODO add your handling code here:
        try {
        int hargaSewaMotor = Integer.parseInt(tfHargasewaform.getText());
        int lamaSewaMotor = Integer.parseInt(tfLamasewaform.getText());
        int biayaHelm = Integer.parseInt(tfBiayahelmform.getText());
        
            if (hargaSewaMotor < 0) { // Periksa apakah input jumlah helm adalah angka positif
                JOptionPane.showMessageDialog(this, "Masukan jumlah helm yang benar!.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                tfJumlahhelmform.requestFocus();
            }else if (lamaSewaMotor < 0) { // Periksa apakah input lama sewa adalah angka positif
                JOptionPane.showMessageDialog(this, "Masukan total lama pinjam yang benar!.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                tfLamasewaform.requestFocus();
            }else if (lamaSewaMotor < 0) { // Periksa apakah input lama sewa adalah angka positif
                JOptionPane.showMessageDialog(this, "Masukan total lama pinjam yang benar!.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                tfLamasewaform.requestFocus();
            }else {
                int totalHarga = (hargaSewaMotor * lamaSewaMotor) + biayaHelm;
                tfTotalbayarform.setText(Integer.toString(totalHarga));
            }
            
        }catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Masukan lama sewa dan jumlah helm.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            tfJumlahhelmform.requestFocus();
        }
    }//GEN-LAST:event_btnHitungtotalformActionPerformed

    private void tfLamasewaformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLamasewaformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLamasewaformActionPerformed

    private void tfNikktpformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNikktpformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNikktpformActionPerformed

    private void tfNikktpformKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNikktpformKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_tfNikktpformKeyTyped

    private void tfLamasewaformKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLamasewaformKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_tfLamasewaformKeyTyped

    private void tfJumlahhelmformKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJumlahhelmformKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_tfJumlahhelmformKeyTyped

    private void tfTanggalformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTanggalformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTanggalformActionPerformed

    private void btnRefreshformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshformActionPerformed
        // TODO add your handling code here:
        tfJumlahhelmform.setText("");
        tfLamasewaform.setText("");
        tfNotransaksiform.setText("");
        tfNamaform.setText("");
        tfNikktpform.setText("");
        taAlamatlengkapform.setText("");
        tfNopolisiform.setText("");
        tfHargasewaform.setText("");
        tfLamasewaform.setText("");
        tfJumlahhelmform.setText("");
        tfBiayahelmform.setText("");
        tfTotalbayarform.setText("");
    }//GEN-LAST:event_btnRefreshformActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSewaMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSewaMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSewaMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSewaMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSewaMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitungtotalform;
    private javax.swing.JButton btnKeluarform;
    private javax.swing.JButton btnRefreshform;
    private javax.swing.JComboBox<String> cbJenismotorform;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextArea taAlamatlengkapform;
    private javax.swing.JTextField tfBiayahelmform;
    private javax.swing.JTextField tfHargasewaform;
    private javax.swing.JTextField tfJumlahhelmform;
    private javax.swing.JTextField tfLamasewaform;
    private javax.swing.JTextField tfNamaform;
    private javax.swing.JTextField tfNikktpform;
    private javax.swing.JTextField tfNopolisiform;
    private javax.swing.JTextField tfNotransaksiform;
    private javax.swing.JTextField tfTanggalform;
    private javax.swing.JTextField tfTotalbayarform;
    // End of variables declaration//GEN-END:variables
}
